### ISSUE TITLE
CoralMask Dataset download

### ISSUE THREAD

**Issue by fxyfengxiaoyi** [zhengziqiang/CoralSCOP#6]
感谢您的出色工作，我想知道如何下载CoralMask这个数据集，我想将它用于有关珊瑚的图像分割研究，希望您能向我提供这个数据集！十分感谢！（我已经填写了下载表单但没有收到回复，可能您忙于工作没有看到。）

**Comment by zhengziqiang** [comment]
Sorry, I usually read the dataset sheet every two or three days (sometimes, it will get some delay). I have sent the link to you.

**Comment by fxyfengxiaoyi** [comment]
> Sorry, I usually read the dataset sheet every two or three days (sometimes, it will get some delay). I have sent the link to you.

Thank you! However, it seems I haven't received the link you sent. Could you please take a few minutes to resend it to me? My email is [1525427088@qq.com](mailto:1525427088@qq.com). I really appreciate it!
